### ISSUE TITLE
Crash: Failed to load the periodic package on update

### ISSUE THREAD

**Issue by sbrl** [Pangoraw/Periodic#3]
I updated from Atom 1.38.2 to 1.39.0, and got this crash :-/

1. ...
2. ...

**Atom**: 1.39.0 x64
**Electron**: 3.1.10
**OS**: Ubuntu 19.04
**Thrown From**: [periodic](https://github.com/pangoraw/periodic) package 0.2.3

### Stack Trace

Failed to load the periodic package

```
At Cannot find module '/home/sbrl/.atom/packages/periodic/node_modules/sqlite3/lib/binding/electron-v3.1-linux-x64/node_sqlite3.node'

Error: Cannot find module '/home/sbrl/.atom/packages/periodic/node_modules/sqlite3/lib/binding/electron-v3.1-linux-x64/node_sqlite3.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155394)
    at Module.require (/app.asar/static/index.js:60:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146719)
    at /packages/periodic/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at /packages/periodic/node_modules/sqlite3/lib/sqlite3.js:190:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146719)
    at /packages/periodic/lib/periodic-view.js:5:24)
    at /packages/periodic/lib/periodic-view.js:8:34)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:71:46)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146719)
    at /packages/periodic/lib/main.js:7:21)
    at /packages/periodic/lib/main.js:26:24)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147410)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150958)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
```

### Commands

```
```

### Non-Core Packages

```
apidoc-snippets 0.1.1 
atom-beautify 0.33.4 
atom-debug-ui 1.0.4 
atom-ide-debugger-native-gdb 0.7.3 
atom-ide-debugger-node 0.7.3 
atom-ide-ui 0.13.0 
atom-ternjs 0.19.1 
atom-typescript 13.2.1 
audio 1.5.7 
aural-coding 1.0.1 
autocomplete-awk 0.1.2 
autocomplete-clang 0.12.0 
autocomplete-glsl 0.2.3 
autocomplete-html-entities 0.2.0 
autocomplete-json 5.5.2 
autocomplete-lua 0.9.2 
autocomplete-math 0.1.1 
autocomplete-modules 2.3.0 
autocomplete-paths 2.12.2 
autocomplete-sql 0.5.0 
busy 0.7.0 
busy-signal 2.0.1 
caniuse 1.0.0 
change-case 0.6.5 
close-tags 0.6.0 
color-picker 2.3.0 
column-select 1.0.1 
css-hyperclick 0.1.5 
cursor-history 0.13.2 
devdocs 0.2.1 
docblockr 0.13.7 
file-icons 2.1.33 
font-preview 0.1.2 
github-user-datatip 0.3.2 
highlight-selected 0.16.0 
hyperclick 0.0.0 
hyperclick-markdown 0.2.2 
hyperlink-hyperclick 3.0.0 
ide-cpp 0.1.0 
ide-csharp 0.6.2 
ide-css 0.3.2 
ide-html 0.5.0 
ide-json 0.2.1 
ide-python 1.4.2 
ide-typescript 0.9.1 
intentions 1.1.5 
js-hyperclick 1.16.0 
language-arduino 0.4.3 
language-awk 0.1.12 
language-bison-improved 0.9.2 
language-bnf 1.1.0 
language-cshtml 0.4.2 
language-diff 0.7.0 
language-gitignore 0.3.0 
language-glsl 2.0.4 
language-gnuplot-atom 0.2.0 
language-ignore 1.8.0 
language-ilasm 0.0.1 
language-ini 1.21.0 
language-latex 1.2.0 
language-lex-flex-new 0.2.1 
language-lua 0.9.11 
language-markdown 0.37.0 
language-openscad 0.4.3 
language-prolog 0.11.0 
language-regexp 1.1.0 
language-rust 0.4.12 
latex-completions 0.3.6 
latex-hyperclick 0.2.0 
line-count-status 0.0.3 
linter 2.3.0 
linter-flake8 2.4.0 
linter-jsonlint 1.4.0 
linter-lua 2.0.0 
linter-php 1.6.1 
linter-phpstan 1.1.1 
linter-tidy 2.4.0 
linter-toml 0.1.1 
linter-ui-default 1.7.1 
linter-ui-plus 0.3.2 
MagicPython 1.1.1 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.7 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
minimap-titles 1.15.0 
move-status-items 0.0.11 
open-in-browser 0.5.2 
package-cop 0.2.10 
pdf-view 0.71.0 
periodic 0.2.3 
php-debug 0.3.5 
php-ide-serenata 4.5.3 
pigments 0.40.2 
project-manager 3.3.7 
project-plus 1.0.0 
protector 0.2.3 
rainbow-csv 0.3.1 
rainbow-tabs 2.5.1 
rainbow-tabs-evolved 2.7.5 
regex-railroad-diagram 0.19.4 
spell-check-urls 0.4.0 
Sublime-Style-Column-Selection 1.7.5 
summer-night-syntax 2.0.1 
switch-header-source 0.34.1 
sync-settings 0.8.6 
teletype 0.13.4 
terminal-tab 0.5.7 
tool-bar 1.1.12 
wordcount 3.1.0 
```

**Comment by sbrl** [comment]
Update: I tried uninstalling and reinstalling it,  but now it won't even install! I get this log output: https://pastebin.com/kfHhqzZx
